[general]
name = "dote"
description = "Manage and consume dotefiles"
generator = "github.com/urfave/cli"

[[command]]
name = "list-profiles"
aliases = [ "ls" ]
description = "List profiles"
action = "listProfiles"

[[command.flags]]
type = "string"
name = "username"
aliases = [ "u" ]
description = "Username"

[[command.flags]]
type = "string"
name = "provider"
aliases = [ "prov" ]
description = "dotefile provider"

[[command.flags]]
type = "string"
name = "repo"
aliases = [ "r" ]
description = "repository source of dotefiles"
