package main

import (
	"log"
	"os"

	"github.com/urfave/cli"
)

// DO NOT MODIFY: generated by github.com/ttacon/toml2cli
// If you need to make changes, update the toml config and then regenerate
// this file.

func main() {
	app := cli.NewApp()
	app.Name = "dote"
	app.Usage = "Manage and consume dotefiles"

	app.Commands = []cli.Command{
		cli.Command{
			Name:        "list-profiles",
			Description: "List profiles",
			Action:      listProfiles,
			Aliases:     []string{"ls"},
			Flags: []cli.Flag{
				cli.StringFlag{
					Name: "username",
				},
				cli.StringFlag{
					Name: "provider",
				},
				cli.StringFlag{
					Name: "repo",
				},
			},
		},
	}
	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}
